Add: four basic subpages.
itsyehudit/nieckovsky_portfolio pull request #3
Opened 2018-01-02 22:01 UTC by itsyehudit

Add: four basic (main) subpages - 'gallery', 'about', 'contact us' and placeholder-ish 'something'.

2018-01-02 22:08 UTC, ktopolski commented
So.. Apart from adding 4 nearly identical pages what do we accomplish?

2018-01-03 04:08 UTC, itsyehudit commented
Merely a foundation for further, more distinct and elaborate changes; an initial commit of sorts for these subpages.

2018-01-03 09:07 UTC, ktopolski requested changes
Whoa, you got me there! I was thinking that the first commit which opened this PR was all we got for the menu this week :)

I think that general direction is good, but I'm getting worried on too many `position absolute`. Let's have a call this week and solve it out.

2018-01-03 09:07 UTC, ktopolski commented on contact.html
> +      Katarzyna Nieckowski<br/><br/>
Avoid using `br` unless it's really needed. Here you can get away with `p` tag, since it takes 100%width by default. If you want double break, consider margin bottom.

2018-01-03 09:07 UTC, ktopolski commented on gallery.html
> +<!DOCTYPE HTML>
We're using html5 tags, I think there's doctype for html5. Not that it matters too much, but just FYI

2018-01-03 09:07 UTC, ktopolski commented on index.html
> +  <body id="main">
Just use class attribute, you should avoid styling by id unless there's no other way. Preferably only if the other way is using `!important `

2018-01-03 09:07 UTC, ktopolski commented on style.css
> +  list-style: none;
Were you looking for `list-style-type: none` on `ul`?

2018-01-03 09:07 UTC, ktopolski commented on style.css
> +  transform: translateY(-50%);
I'm a little puzzled, why!

2018-01-03 23:39 UTC, itsyehudit commented on contact.html
> +      Katarzyna Nieckowski<br/><br/>
Okay, of course, I can do that, yet still, I'm curious what's the reason, especially since using p tag would never be my intuitive choice?

2018-01-03 23:42 UTC, itsyehudit commented on gallery.html
> +<!DOCTYPE HTML>
Yes, yes there is, and THAT'S what it looks like. ^^

2018-01-03 23:51 UTC, itsyehudit commented on index.html
> +  <body id="main">
Okay, "better safe than sorry" overruled "don't use id unless you have to" a bit, just wanted to amp specificity up a bit.

2018-01-04 00:08 UTC, itsyehudit commented on style.css
> +  list-style: none;
Hm. Curiously enough - it works. Actually, it does not matter if it's under the ul or li selector... But to keep it all coherent, I'll change it.

2018-01-04 00:19 UTC, itsyehudit commented on style.css
> +  transform: translateY(-50%);
Keep in mind I'm still looking for the best ways to code and to keep things as close to the design as possible. This means I might come up with some peculiar ways of coping with issues like "put this element in the middle of the layout and make it stay there and if possible make it responsive and try to remember what you were advised NOT to do".
This does the trick. But not to worry, I've already come up with new ideas how to achieve the same result, I'll keep you posted. :)

2018-01-04 23:37 UTC, ktopolski commented on contact.html
> +      Katarzyna Nieckowski<br/><br/>
Actually, I've made up my mind the other way around. I was a little afraid of you getting used to insert multiple `br` tags to make space between lines. I think here it's the easiest and sufficient way to achieve your layout. Using p tags would only add styles without any learning value.

2018-01-04 23:37 UTC, ktopolski commented on gallery.html
> +<!DOCTYPE HTML>
nice one then :)

2018-01-04 23:38 UTC, ktopolski commented on index.html
> +  <body id="main">
YAGNI should always overrule "better safe than sorry". You're always safe with git on the board, that's what VCS is for :)

2018-01-04 23:41 UTC, ktopolski commented
Hey!

After one talk and some evening CSS fun, I pushed branch with cleanups to https://github.com/itsyehudit/nieckovsky_portfolio/tree/subpages-cleanups.

I got rid of absolute aligning by using flexbox. I reviewed our options and flex suprisingly seems like the simpliest and cleanest solution.

I would like you to try and achieve same results as I did with our codebase without copying the code. Get a quick look of how I handled things, try to achieve same thing yourself, if you're stuck, then take another look.

2018-01-12 08:04 UTC, ktopolski approved these changes
Very well done Kate! That's some progress :).

I approve this PR. Please squash changes and push here, I will merge then.

2018-01-20 15:04 UTC, merged